-- =====================================================================
-- Hardware Storage System - Seed data
-- =====================================================================
USE hardware_storage;

-- Roles
INSERT INTO roles (role_name, description) VALUES
  ('admin',    'Full access to all features'),
  ('manager',  'Can manage products, stock, and view reports'),
  ('staff',    'Day-to-day operations and orders');

-- NOTE: password hashes below are bcrypt hashes for the literal password 'password123'.
-- They are generated by scripts/init_db.py when --reseed is used. The placeholder
-- hash below works for 'password123' (bcrypt, cost 12). The init script will
-- re-hash if needed.
-- Employees (4 staff)
INSERT INTO employees (username, password_hash, full_name, email, phone, role_id, is_active, hired_on) VALUES
  ('admin',   '$2b$12$wq9bU8r6XwQwq9bU8r6XweH0r6XwHwq9bU8r6XwHwq9bU8r6XwHwq', 'System Administrator', 'admin@hwstore.local',   '0917-111-1111', 1, 1, '2023-01-15'),
  ('mlopez',  '$2b$12$wq9bU8r6XwQwq9bU8r6XweH0r6XwHwq9bU8r6XwHwq9bU8r6XwHwq', 'Maria Lopez',          'maria@hwstore.local',   '0917-222-2222', 2, 1, '2023-03-10'),
  ('jdcruz',  '$2b$12$wq9bU8r6XwQwq9bU8r6XweH0r6XwHwq9bU8r6XwHwq9bU8r6XwHwq', 'Juan Dela Cruz',       'juan@hwstore.local',    '0917-333-3333', 3, 1, '2024-02-20'),
  ('asantos', '$2b$12$wq9bU8r6XwQwq9bU8r6XweH0r6XwHwq9bU8r6XwHwq9bU8r6XwHwq', 'Ana Santos',           'ana@hwstore.local',     '0917-444-4444', 3, 1, '2024-06-01');

-- Categories
INSERT INTO categories (name, description) VALUES
  ('CPU',        'Processors / central processing units'),
  ('GPU',        'Graphics cards'),
  ('RAM',        'Memory modules'),
  ('Storage',    'SSDs, HDDs, NVMe drives'),
  ('Motherboard','Mainboards'),
  ('PSU',        'Power supplies'),
  ('Peripheral', 'Keyboards, mice, headsets');

-- Suppliers
INSERT INTO suppliers (name, contact_name, email, phone, address, country) VALUES
  ('TechSource Inc.',     'Carlos Reyes',   'sales@techsource.example',  '02-8000-1111', '123 Ortigas Ave, Pasig',    'Philippines'),
  ('NorthBridge Trading', 'Liza Tan',       'liza@nbridge.example',      '02-8000-2222', '88 EDSA, Quezon City',      'Philippines'),
  ('PCParts Asia',        'Kenji Tanaka',   'kenji@pcparts.example',     '+81-3-1234',   '5-1 Akihabara, Tokyo',      'Japan'),
  ('Global Components',   'Sarah Miller',   'sarah@globalc.example',     '+1-415-5000',  '500 Market St, San Francisco', 'USA');

-- Warehouses
INSERT INTO warehouses (name, city, address, capacity) VALUES
  ('Main Warehouse', 'Manila',     '12 Roxas Blvd, Manila',    5000),
  ('North Annex',    'Quezon City','45 Commonwealth Ave',      2000),
  ('South Hub',      'Makati',     '8 Ayala Ave, Makati',      3000);

-- Products
INSERT INTO products (sku, name, category_id, supplier_id, unit_price, description) VALUES
  ('CPU-INT-13600K','Intel Core i5-13600K',     1, 1, 18500.00, '14-core CPU, LGA1700'),
  ('CPU-AMD-7600X', 'AMD Ryzen 5 7600X',        1, 2, 16500.00, '6-core CPU, AM5'),
  ('GPU-NV-4060',   'NVIDIA GeForce RTX 4060',  2, 1, 23000.00, '8GB GDDR6'),
  ('GPU-AMD-7700XT','AMD Radeon RX 7700 XT',    2, 4, 28500.00, '12GB GDDR6'),
  ('RAM-COR-32GB',  'Corsair Vengeance 32GB DDR5', 3, 3, 7800.00, '2x16GB 5600MHz'),
  ('RAM-KIN-16GB',  'Kingston Fury 16GB DDR4',  3, 2, 3200.00, '2x8GB 3200MHz'),
  ('SSD-SAM-1TB',   'Samsung 990 Pro 1TB NVMe', 4, 3, 6500.00, 'PCIe 4.0 NVMe'),
  ('SSD-WD-2TB',    'WD Black SN850X 2TB',      4, 4, 11500.00, 'PCIe 4.0 NVMe'),
  ('MB-ASUS-Z790',  'ASUS ROG Strix Z790-F',    5, 1, 19500.00, 'LGA1700 motherboard'),
  ('MB-MSI-B650',   'MSI MAG B650 Tomahawk',    5, 2, 13500.00, 'AM5 motherboard'),
  ('PSU-COR-850W',  'Corsair RM850x 850W',      6, 3, 7500.00, '80+ Gold, fully modular'),
  ('PSU-SEA-650W',  'Seasonic Focus 650W',      6, 4, 5500.00, '80+ Gold'),
  ('KB-LOG-G915',   'Logitech G915 Keyboard',   7, 4, 9500.00, 'Wireless mechanical'),
  ('MS-RAZ-V3',     'Razer DeathAdder V3',      7, 1, 3500.00, 'Wired gaming mouse');

-- Stock (per warehouse)
INSERT INTO stock (product_id, warehouse_id, quantity, reorder_level) VALUES
  (1, 1, 25, 5), (1, 2, 10, 5), (1, 3, 8, 5),
  (2, 1, 30, 5), (2, 2, 12, 5),
  (3, 1, 15, 3), (3, 3, 6, 3),
  (4, 1, 2, 3),
  (4, 3, 1, 3),
  (5, 1, 40, 10), (5, 2, 20, 10), (5, 3, 15, 10),
  (6, 1, 60, 10),
  (7, 1, 22, 5), (7, 2, 18, 5),
  (8, 1, 14, 5),
  (9, 1, 9, 3),
  (10, 2, 11, 3),
  (11, 1, 28, 5), (11, 3, 12, 5),
  (12, 1, 35, 5),
  (13, 2, 18, 4),
  (14, 1, 50, 8), (14, 2, 40, 8);

-- Customers
INSERT INTO customers (full_name, email, phone, address, city, customer_type) VALUES
  ('Pedro Garcia',     'pedro@example.com',  '0917-555-1001', '1 Sunshine St',    'Manila',     'retail'),
  ('TechCity Retail',  'orders@techcity.example', '02-8800-9000', '300 Makati Ave', 'Makati',    'wholesale'),
  ('Anna Reyes',       'anna@example.com',   '0917-555-1002', '22 Greenway Ave',  'Quezon City','retail'),
  ('CompuWorld Corp.', 'sales@compuworld.example', '02-8700-2222', '88 Ortigas',    'Pasig',     'wholesale'),
  ('Mike Chen',        'mike@example.com',   '0917-555-1003', '99 Burgos St',     'Makati',     'retail'),
  ('Lara Tan',         'lara@example.com',   '0917-555-1004', '12 Roxas Blvd',    'Manila',     'retail'),
  ('Builders Co.',     'orders@builders.example', '02-8800-3333', '101 EDSA',     'Quezon City','wholesale');

-- Orders
INSERT INTO orders (customer_id, employee_id, order_date, status, total_amount) VALUES
  (1, 3, '2025-01-15 10:30:00', 'paid',     21700.00),
  (2, 2, '2025-01-20 14:00:00', 'shipped',  85000.00),
  (3, 3, '2025-02-05 11:15:00', 'pending',  10800.00),
  (4, 2, '2025-02-12 09:00:00', 'paid',     61500.00),
  (5, 4, '2025-03-01 16:45:00', 'cancelled', 7500.00),
  (1, 4, '2025-03-15 13:20:00', 'paid',     34000.00);

-- Order items
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES
  (1, 1, 1, 18500.00), (1, 14, 1, 3500.00),       -- order 1: CPU + mouse
  (2, 3, 2, 23000.00), (2, 5, 5, 7800.00),        -- order 2: GPUs + RAM
  (3, 6, 2, 3200.00),  (3, 11, 1, 7500.00),       -- order 3: RAM + PSU (pending)
  (4, 4, 1, 28500.00), (4, 9, 1, 19500.00), (4, 7, 2, 6500.00), -- order 4
  (5, 11, 1, 7500.00), -- order 5 cancelled
  (6, 8, 2, 11500.00), (6, 13, 1, 9500.00), (6, 6, 1, 3200.00); -- order 6
